// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodels

const TableNameBroadcastMessage = "broadcast_messages"

// BroadcastMessage mapped from table <broadcast_messages>
type BroadcastMessage struct {
	ID      int32   `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	IsSent  bool    `gorm:"column:is_sent;type:boolean;not null" json:"is_sent"`
	Message *string `gorm:"column:message;type:text" json:"message"`
	Image   *string `gorm:"column:image;type:uuid" json:"image"`
}

// TableName BroadcastMessage's table name
func (*BroadcastMessage) TableName() string {
	return TableNameBroadcastMessage
}
