// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodels

const TableNameBroadcastMessages = "broadcast_messages"

// BroadcastMessages mapped from table <broadcast_messages>
type BroadcastMessages struct {
	ID      int32   `gorm:"column:id;type:integer;primaryKey;autoIncrement:true" json:"id"`
	IsSent  bool    `gorm:"column:is_sent;type:boolean;not null" json:"is_sent"`
	Message *string `gorm:"column:message;type:text" json:"message"`
	Image   *string `gorm:"column:image;type:uuid" json:"image"`
}

// TableName BroadcastMessages's table name
func (*BroadcastMessages) TableName() string {
	return TableNameBroadcastMessages
}
