// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodels

const TableNameButton = "buttons"

// Button mapped from table <buttons>
type Button struct {
	ID      string  `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Sort    int32   `gorm:"column:sort;type:integer;not null;default:1" json:"sort"`
	Name    string  `gorm:"column:name;type:character varying(255);not null;default:NULL" json:"name"`
	Message *string `gorm:"column:message;type:text" json:"message"`
	Image   *string `gorm:"column:image;type:uuid" json:"image"`
}

// TableName Button's table name
func (*Button) TableName() string {
	return TableNameButton
}
