// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	Admin             *admin
	BroadcastMessages *broadcastMessages
	Buttons           *buttons
	File              *file
	User              *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Admin = &Q.Admin
	BroadcastMessages = &Q.BroadcastMessages
	Buttons = &Q.Buttons
	File = &Q.File
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		Admin:             newAdmin(db, opts...),
		BroadcastMessages: newBroadcastMessages(db, opts...),
		Buttons:           newButtons(db, opts...),
		File:              newFile(db, opts...),
		User:              newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin             admin
	BroadcastMessages broadcastMessages
	Buttons           buttons
	File              file
	User              user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		Admin:             q.Admin.clone(db),
		BroadcastMessages: q.BroadcastMessages.clone(db),
		Buttons:           q.Buttons.clone(db),
		File:              q.File.clone(db),
		User:              q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		Admin:             q.Admin.replaceDB(db),
		BroadcastMessages: q.BroadcastMessages.replaceDB(db),
		Buttons:           q.Buttons.replaceDB(db),
		File:              q.File.replaceDB(db),
		User:              q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Admin             IAdminDo
	BroadcastMessages IBroadcastMessagesDo
	Buttons           IButtonsDo
	File              IFileDo
	User              IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:             q.Admin.WithContext(ctx),
		BroadcastMessages: q.BroadcastMessages.WithContext(ctx),
		Buttons:           q.Buttons.WithContext(ctx),
		File:              q.File.WithContext(ctx),
		User:              q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
